service: serverless-boiler
provider:
  name: aws
  runtime: nodejs18.x
functions:
  api:
    handler: dist/handler.main
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
plugins:
  - serverless-offline
  - serverless-offline-watcher

custom:
  serverless-offline-watcher:
    - path: app.ts
      command: echo "app.ts was modified!"
    - path: handler.ts
      command: echo "handler.ts was modified!"
    - path:
      - routes
      command:
        - echo "routes folder or ts file in cow folder was modified!"