service: serverless-boiler
provider:
  name: aws
  runtime: nodejs18.x
functions:
  api:
    handler: handler.main
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
plugins:
  - serverless-offline
