service: serverless-boiler
provider:
  name: aws
  runtime: nodejs18.x
functions:
  api:
    handler: handler.main
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
plugins:
  - serverless-offline
  - serverless-offline-watcher

custom:
  serverless-offline-watcher:
    - path: app.js
      command: echo "app.js was modified!"
    - path: handler.js
      command: echo "handler.js was modified!"
    - path:
      - routes
      command:
        - echo "routes folder or js file in cow folder was modified!"